### ISSUE TITLE
Can't close any of game menus

### ISSUE THREAD

**Issue by Andrej730** [Hero-Wars-Dev-Team/Hero-Wars#13]
Any game menu can not be closed by pressing 0 and even typing in console "menuselect 0". After some google search i found that issue is related to source-pythons menus package (http://goo.gl/4ytIgR; Also seen a same issue in your thread - http://goo.gl/hREqPw). So, need to find and implement a solution to solve this - for example, on some wcs servers i seen that they just reduced the amount of options in menus and place close option to "9" button.
Also when i try to run hw on my server find some typeerrors when opening menus about skills. Have fixed them in my fork - https://goo.gl/L1y5Vg.

**Comment by MarkusMeskanen** [comment]
Hey Andrej730!

As you mentioned, the menu problem is a Source.Python sided thing, and so far we haven't done anything to bypass the problem. If there will be no solution from Source.Python's side in the near future, we might eventually move the selection numbers to 789 instead of 890. But binding "menuselect 0" works fine for me on CS:GO, so we haven't done anything just yet.

I've fixed the type errors, thank you very much for reporting the bug.
